import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import AdminLayout from '../components/layout/AdminLayout';
import { submissionService, Submission } from '../services/submissionService';

export default function Submissions() {
  const [type, setType] = useState<'article' | 'course'>('article'); const [items, setItems] = useState<Submission[]>([]); const [selected, setSelected] = useState<Submission | null>(null); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); setItems(await submissionService.list(type)); } catch { toast.error('تعذر تحميل قائمة المراجعة'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [type]);
  const review = async (item: Submission) => { try { setSelected(await submissionService.get(type, item.id)); setReason(''); } catch { toast.error('تعذر تحميل المحتوى'); } };
  const approve = async () => { if (!selected) return; try { await submissionService.approve(type, selected.id); toast.success('تم اعتماد المحتوى'); setSelected(null); load(); } catch (error: any) { toast.error(error.message || 'تعذر الاعتماد'); } };
  const reject = async () => { if (!selected || !reason.trim()) return toast.error('اكتب سبب الرفض'); try { await submissionService.reject(type, selected.id, reason); toast.success('تم رفض المحتوى'); setSelected(null); load(); } catch (error: any) { toast.error(error.message || 'تعذر الرفض'); } };
  return <AdminLayout><div className="space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-3xl font-extrabold">طلبات المحتوى</h1><p className="text-gray-500 mt-1">راجع المحتوى قبل نشره على المنصة.</p></div><select value={type} onChange={e => setType(e.target.value as 'article' | 'course')} className="border rounded-xl p-2"><option value="article">مقالات</option><option value="course">دورات</option></select></div>{loading ? <p>جاري التحميل...</p> : items.length === 0 ? <div className="bg-white rounded-2xl p-10 text-center text-gray-500">لا توجد طلبات معلقة.</div> : <div className="bg-white rounded-2xl overflow-hidden"><table className="w-full text-right"><thead className="bg-gray-50"><tr><th className="p-4">العنوان</th><th className="p-4">المرسل</th><th className="p-4">النوع</th><th className="p-4"></th></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t"><td className="p-4 font-medium">{item.title}</td><td className="p-4">{item.submitter?.display_name || 'غير معروف'}</td><td className="p-4">{item.audience === 'public' ? `عام / ${item.visibility === 'unlisted' ? 'غير مدرج' : 'مدرج'}` : 'مهني'}</td><td className="p-4"><button onClick={() => review(item)} className="bg-blue-600 text-white px-4 py-2 rounded-xl">مراجعة</button></td></tr>)}</tbody></table></div>}{selected && <div className="fixed inset-0 bg-black/40 z-50 p-4 flex justify-center items-center"><div className="bg-white rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-auto p-6"><h2 className="text-2xl font-bold">{selected.title}</h2><p className="text-sm text-gray-500 mt-2">{selected.audience === 'public' ? `محتوى عام — ${selected.visibility === 'unlisted' ? 'غير مدرج / مشاركة فقط' : 'مدرج'}` : 'محتوى مهني'}</p>{selected.cover_image && <img src={selected.cover_image} alt="" className="mt-4 max-h-64 rounded-xl" />}{selected.excerpt && <p className="mt-4 font-medium">{selected.excerpt}</p>}{selected.content ? <div className="mt-4 prose max-w-none" dangerouslySetInnerHTML={{ __html: selected.content }} /> : <p className="mt-4 whitespace-pre-wrap">{selected.description}</p>}<textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="سبب الرفض (مطلوب عند الرفض)" className="w-full mt-6 border rounded-xl p-3 min-h-24" /><div className="flex gap-3 mt-4"><button onClick={approve} className="bg-green-600 text-white px-5 py-2 rounded-xl">اعتماد</button><button onClick={reject} className="bg-red-600 text-white px-5 py-2 rounded-xl">رفض</button><button onClick={() => setSelected(null)} className="border px-5 py-2 rounded-xl">إغلاق</button></div></div></div>}</div></AdminLayout>;
}
