import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { creatorApi } from '../../lib/api';

export default function ArticleEditorPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [form, setForm] = useState<Record<string, string>>({ title: '', excerpt: '', content: '', cover_image: '', tags: '', audience: 'professional', visibility: 'listed' });
  useEffect(() => { if (id) creatorApi.getArticles().then(items => { const item = items.find((entry: any) => entry.id === id); if (item) setForm({ ...item, tags: (item.tags || []).join(',') }); }).catch(() => toast.error('تعذر تحميل المقال')); }, [id]);
  const set = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const payload = { ...form, tags: form.tags.split(',').map(tag => tag.trim()).filter(Boolean) }; id ? await creatorApi.updateArticle(id, payload) : await creatorApi.createArticle(payload); toast.success('تم حفظ المسودة'); navigate('/account'); } catch (error: any) { toast.error(error.message || 'تعذر حفظ المقال'); } };
  return <div className="layout-modern py-10"><form onSubmit={save} className="container-modern max-w-4xl bg-white rounded-2xl shadow-sm p-6 space-y-4"><h1 className="text-2xl font-bold">{id ? 'تعديل المقال' : 'مقال جديد'}</h1><input required placeholder="العنوان" value={form.title} onChange={e => set('title', e.target.value)} className="input-modern" /><textarea required placeholder="الملخص" value={form.excerpt} onChange={e => set('excerpt', e.target.value)} className="input-modern min-h-24" /><input placeholder="رابط صورة الغلاف" value={form.cover_image} onChange={e => set('cover_image', e.target.value)} className="input-modern" /><input placeholder="الوسوم، مفصولة بفاصلة" value={form.tags} onChange={e => set('tags', e.target.value)} className="input-modern" /><select value={form.audience} onChange={e => { set('audience', e.target.value); if (e.target.value === 'professional') set('visibility', 'listed'); }} className="input-modern"><option value="professional">للمحترفين</option><option value="public">للجمهور العام</option></select>{form.audience === 'public' && <select value={form.visibility} onChange={e => set('visibility', e.target.value)} className="input-modern"><option value="listed">مدرج في قسم الصحة العامة</option><option value="unlisted">غير مدرج — مشاركة بالرابط فقط</option></select>}<textarea required placeholder="اكتب محتوى المقال بصيغة HTML" value={form.content} onChange={e => set('content', e.target.value)} className="input-modern min-h-80" /><button className="btn-primary">حفظ كمسودة</button></form></div>;
}
